### ISSUE TITLE
Exception thrown when redacting objects paths that contain a hyphen

### ISSUE THREAD

**Issue by UnbounDev** [pinojs/pino#480]
Using `pino@5.0.1` and `fast-redact@1.1.13`.

This seems to be an issue specifically w/ the `pino` validation check, as the below test script shows that redaction via `fast-redact` works while the same arguments in `pino` will throw an exception:

```
// test fast-redact and hyphenated object path
const fastRedact = require('fast-redact')
const fauxRequest = {
  headers: {
    'x-access-token': 'super-secret',
    host: 'http://example.com',
    cookie: `oh oh we don't want this exposed in logs in etc.`,
    referer: `if we're cool maybe we'll even redact this`
  }
}
const redact = fastRedact({
  paths: ['headers.cookie', 'headers.referer', 'headers["x-access-token"]']
})

console.log('\n');
console.log(redact(fauxRequest))
console.log('\n');

// test pino instantiation w/ the same arguments for redaction
const logger = require('pino')({ redact: { paths: ['headers.cookie', 'headers.referer', 'headers["x-access-token"]' ] } });
```

-->

```

{"headers":{"x-access-token":"[REDACTED]","host":"http://example.com","cookie":"[REDACTED]","referer":"[REDACTED]"}}


/home/austin/code/common/node_modules/fast-redact/lib/validator.js:38
        throw Error(ERR_INVALID_PATH(s))
        ^

Error: fast-redact – Invalid path ("x-access-token"])
    at paths.forEach (/home/austin/code/common/node_modules/fast-redact/lib/validator.js:38:15)
    at Array.forEach (<anonymous>)
    at validate (/home/austin/code/common/node_modules/fast-redact/lib/validator.js:18:11)
    at fastRedact (/home/austin/code/common/node_modules/fast-redact/index.js:36:3)
    at Object.keys.reduce (/home/austin/code/common/node_modules/pino/lib/redaction.js:44:17)
    at Array.reduce (<anonymous>)
    at redaction (/home/austin/code/common/node_modules/pino/lib/redaction.js:41:29)
    at pino (/home/austin/code/common/node_modules/pino/pino.js:65:33)
    at Object.<anonymous> (/home/austin/code/common/scratch.js:18:31)
    at Module._compile (module.js:652:30)

```

**Comment by davidmarkclements** [comment]
this requires a fix in fast-redact, it's in progress, see https://github.com/davidmarkclements/fast-redact/pull/2

**Comment by davidmarkclements** [comment]
(it will also require a much smaller fix in pino core)

**Comment by davidmarkclements** [comment]
resolved in #482

**Comment by thetumper** [comment]
Using pino 6.8.0, yet still seeing this issue:

2021-02-08T22:45:10.373Z	098669fd-71c0-45a2-9589-b7d933a2206f	ERROR	Error: pino – redact paths array contains an invalid path (headers.x-api-key)    at paths.forEach (/var/task/node_modules/fast-redact/lib/validator.js:34:15)    at Array.forEach (<anonymous>)    at validate (/var/task/node_modules/fast-redact/lib/validator.js:14:11)    at handle (/var/task/node_modules/pino/lib/redaction.js:105:5)    at redaction (/var/task/node_modules/pino/lib/redaction.js:16:29)    at pino (/var/task/node_modules/pino/pino.js:129:33)    at Object.(anonymous function).n [as debug]
...etc....

**Comment by thetumper** [comment]
Ok - discovered that bracket notation is valid for this path, but dot notation is not.  I.e., 'headers.x-api-key' will fail, but, 'headers[x-api-key]' is valid and works as expected.  Not sure if that is known/intended?  But it was not obvious to my (mis?)reading of the docs.

**Comment by mcollina** [comment]
would you like to send a PR to update the docs?
